### ISSUE TITLE
mstransform does not respect `keepmms` option

### ISSUE THREAD

**Issue by Kitchi** [idia-astro/pipelines#39]
When `keepmms = False`, the final `split.py` now calls `mstransform` with `createmms=False`. However this does not convert an `mms` back to an `ms`. It appears the only task that can do this is `split`.

**Comment by Jordatious** [comment]
From memory, our solution to this was to call `mstransform` at the beginning of the pipeline, instead of `partition`, so that (to address #32) we can include the `WEIGHT_SPECTRUM` column in the MMS right from the beginning (assuming `clearcal` or another task doesn't remove it). And then we can change this back to `split` when splitting out the fields at the end of the pipeline, restoring the desired functionality of `keepmms`.

**Comment by Jordatious** [comment]
Fixed in 728c13490b8b23e735e22f94b23077ce3f0ecc62.
