### ISSUE TITLE
When making some imaging batch files, mem parameter isn't respected

### ISSUE THREAD

**Issue by dentalfloss1** [idia-astro/pipelines#49]
I was using the experimental imaging-selfcal pipeline and ran into the following issue. The following batch files always use 232GB for the memory parameter instead of what's specified in the configuration file:
run_bdsf.sbatch
selfcal_part2.sbatch
Not sure if that was intentional or not. Test folder used for this is located at /scratch2/users/sarahchastain/testdir
Calling 'source /idia/software/pipelines/master/setup.sh' should be v1.1

**Comment by Jordatious** [comment]
Hey @dentalfloss1, whenever all the CPUs from a node are being used in an sbatch script, the pipeline will overwrite the memory argument to use all of the memory, since the memory on those nodes is inaccessible to any other jobs if all of its CPUs are being used. During the tclean and PyBDSF scripts, the pipeline also attempts to use all the CPUs (always for PyBDSF, and for tclean, if the number of tasks is <= 16). You can overwrite this by editing the sbatch scripts before running `./submit_pipeline.sh`.

**Comment by dentalfloss1** [comment]
Gotchya. I will say that even when you specify the "HighMem" partition it still reserves 232 GB instead of 480 GB

**Comment by Jordatious** [comment]
Yep, thanks, I've already patched that elsewhere, which will soon make its way into the Master branch 👍
