### ISSUE TITLE
Error in plot_solutions script

### ISSUE THREAD

**Issue by aishrimc** [idia-astro/pipelines#56]
Hi, 
I am using the processMeerKAT pipeline (version 2.0) in ilifu, and have come across a problem in plotting the gain tables. The plot_solutions.py script is not added by default to the configuration file. I edited the file and added it by hand (`scripts =[(flag_round_1.py, True, ' '), ..., ('quick_tclean.py', True, ''), ('plot_solutions.py', False, '')]`).  However, the plotting fails, even after all the previous steps have run successfully. The output for `findErrors.sh` shows `srun: error: compute-017: task 0: Exited with exit code 127`.  In the output logs, `plot_solutions-4967475.out` has the message `/usr/bin/xvfb-run: 184: casa: not found`. It seems that casa does not exist in the path `/usr/bin/xvfb-run`. However, that still does not explain why the plot file is not written to the config file.

**Comment by Jordatious** [comment]
Hi @aishrimc, thanks for raising this issue. We haven't supported that script for a while since moving onto CASA 6 (I should have removed it sorry), mainly because plotms did not work for CASA 6 for some time. However, we've recently [had some success with our own hackery](https://docs.ilifu.ac.za/#/astronomy/astronomy_software?id=casa-plotms)! So I can push some patches to this script making use of plotms after I've been able to test it a little, perhaps on Monday. I can also push this `fastplot.py` script I've been using as an alternative, if that's of interest. In the interim, can you make your own calls of `plotms`?

**Comment by aishrimc** [comment]
Oh sure, I can do my own plotms. Thanks for pointing out the cause of the issue.
